fix: Emoji_compat (#5)
* Create FileChooser

* Reduce warnings

* Remove unused members

* Remove unused methods

* Add FontChooser

* Update strings.xml

a few grammar corrections

* Update README.md

just some English fixes

* Add legal notices

* Upgrade to 2.4.0

* Create strings.xml

* Update strings.xml

* create ci config

* Update config.yml

* Update strings.xml

* Update strings.xml

* Update strings.xml

* Update strings.xml

* Support Unicode 12.0.0 and 12.1.0

* Show UTF-8 byte sequence

* Update version to 2.5.0

* Remove non-translatable strings

* Update targetSdkVersion

* Update CI docker container

* Updated sv/strings.xml

Updated sv/strings.xml to match the default strings.xml. Removed arrays missing from the default, and added missing translations.

* Update to U12 and some fixes

google.com is unreachable in China.

* small fixes

* Update strings.xml

* Update strings.xml

* update namedb to 13.0

* update hard-coded data to 13.0

* add emoji version switch

* add 13.0 to version setting

* update app version

* update .gitignore

* migrate to latest Android Studio

* update db

* support showing emoji version

* add AdMob

* useAndroidX

* fix EllipsizeMaxLines

* update versionCode

* update admob id

* fix theme bug

* update noto url

* update version code

* replace `play-services-ads` with `play-services-ads-lite`

* enable size optimization

* fix compatibility problem

* fix IllegalStateException

* Arrays with string reference

Array simply referencing string values, allowing only parts of the array to be translated

* Updating for array strings

* Updating for array strings

* Updating for array strings

* remove deprecated api support

* resolve compilation errors

* make some resource untranslatable and remove redundant resources

* update Japanese translation

* I gave up formatting `version_latest` :(

* move resources into an appropriate file

* add missing translation

* move zh to zh-rCN

* add zh-rTW translation

* Update version to 2.7.0

* Add round and adaptive icon resources

* Apply round and adaptive icon resources

* Use Storage Access Framework to choose a font

* Delete .zip in FilesDir

* Improve dialog title for .zip in FilesDir

* Use inputType attribute instead of deprecated numeric in setting.xml

* Delete commented out resources in setting.xml

* Enable input method by default

* Settings for EmojiCompat

* Initialize EmojiCompat

* Use EmojiAppCompatEditText view

* Render EmojiSpan in CharacterView

* Implement auto-restart

* fix: Localize_ka (#3)

* Update version

* Update SDK version

* Fix compileSdkVersion

* Update strings.xml

* Create strings.xml

* Refactor: replace GridView with AbsListView

* Update gradle

* Add DSLV dependency

* Implement with DragSortListView

* Rewrite tab setting with DragSortListView

* Update verison

* Fix IllegalStateException from android.widget.ListView.layoutChildren

* Update version

* Convert to Kotlin

* Refactor

* Refactor

* Refactor

* Refactor

* Update strings.xml

* Refactor

* Fix a bug that the list tab can be hidden

* Add bottom padding to last item so that all items can be visible even if UI scroll is enabled

The last few rows of lists might be hidden because of UI scroll.
Users often don't notice UI scroll is enabled.
This commit adds extra padding to the last item of lists and all items can be visible even if UI scroll is enabled and not scrolled.

* Better tab setting styling

* Drag handle drawable for DragSortListView

* Set float background of DragSortListView

* Update drawables

* Make emojis searchable from find tab

* Fix null reference errors on CompleteAdapter

* Limit auto-complete words

* Update SDK verison

* Updating Swedish (sv) translation

* Split into variants for "play" and "fdroid"

play: Works exactly as before.
fdroid: does not contain any ads/ad libraries making the app compatible
  with FDroid again.

Both variants share the same application ID so users of both platforms
will get seamless upgrades.

Fixes #48.

* This fixes NewApi Lint error: https://app.circleci.com/pipelines/github/Ryosuke839/UnicodePad/87/workflows/eefa0252-f620-44b3-bcf9-3532766fde80/jobs/82

* Increase JVM memory

* Add script to build namedb

* Implement ACTION_PROCESS_TEXT intent

* Implement locale selection for font rendering

* Create strings.xml

* Implement filterable Spinner

* Use FilterableSpinner for block list

* Implement setting I/O

* Add locale to setting I/O

* Update database

* Add version 14

* Support 14 blocks

* Update Noto URL

* Move Georgian resource into right place

* Remove bad resources from ka

* fix: develop (#2)

* Update version code

* Update Unicode copyright

* Resolve warnings

* Add Japanese translation

* Fix crashes found in pre-release tests

* Update version to 2.10.1

* Fix NullPointerException on onEditorAction

* Fix font rendering in large view

* Update .gitignore

* Update .idea files

* Bump version to 2.10.2

* Fix IndexOutOfBoundsException on FontChooser.add

* Avoid NumberFormatException

* Fix IllegalStateException from ViewPager

* Bump version to 2.10.4

* fix: Master (#1)

Co-authored-by: Ryosuke839 <ryosukem16@gmail.com>

Co-authored-by: Ryosuke839 <ryosukem16@gmail.com>

Co-authored-by: Ryosuke839 <ryosukem16@gmail.com>
Co-authored-by: yn0793 <32827924+yn0793@users.noreply.github.com>
Co-authored-by: Coding-Young <73321845+Coding-Young@users.noreply.github.com>
Co-authored-by: Liggliluff <liggliluff@gmail.com>
Co-authored-by: Thomas Weißschuh <thomas@t-8ch.de>
Co-authored-by: Luka Mamukashvili <57063715+UltraStudioLTD@users.noreply.github.com>

Co-authored-by: Ryosuke839 <ryosukem16@gmail.com>
Co-authored-by: TacoTheDank <SkytkRSfan3895@gmail.com>
Co-authored-by: yn0793 <32827924+yn0793@users.noreply.github.com>
Co-authored-by: Liggliluff <liggliluff@gmail.com>
Co-authored-by: Coding-Young <73321845+Coding-Young@users.noreply.github.com>
Co-authored-by: Thomas Weißschuh <thomas@t-8ch.de>
Co-authored-by: Luka Mamukashvili <57063715+UltraStudioLTD@users.noreply.github.com>